added cms_audio
blutui/dev.blutui.com pull request #207
Opened 2024-02-05 02:08 UTC by ruslan-pan

2024-07-16 23:06 UTC, jayan-blutui commented on src/navigation/documentation.ts
> +                url: '/docs/canvas/functions/canopy/cms',
This is not a Canopy function.

2024-07-18 23:03 UTC, dion-blutui commented on src/navigation/documentation.ts
> +                url: '/docs/canvas/functions/canopy/cms',
Cool I will pull it out

2024-07-21 23:34 UTC, jayan-blutui requested changes

2024-07-21 23:34 UTC, jayan-blutui commented on src/pages/docs/canvas/functions/canopy/cms-audio.md
> +{{ cms_audio(name, { controls: ..., autoplay: ..., sources: [{ url:'...', type:'...' },{ url: '...', type: '...' }], class: '...' }) }}
```suggestion
{{ cms_audio(name, { controls: ..., autoplay: ..., sources: [{ url: '...', type: '...' }, { url: '...', type: '...' }], class: '...' }) }}
```

2024-07-21 23:34 UTC, jayan-blutui commented on src/pages/docs/canvas/functions/canopy/cms-button.md
> +{{ cms_button('mybutton', { text: 'Blutui AI Components', url: 'https://blutui.ai/', class: 'bg-blue-500 text-white rounded hover:bg-blue-700',  opens_new_tab: true }) }}
```suggestion
{{ cms_button('mybutton', { text: 'Blutui AI Components', url: 'https://blutui.ai/', class: 'bg-blue-500 text-white rounded hover:bg-blue-700', opens_new_tab: true }) }}
```

2024-07-21 23:34 UTC, jayan-blutui commented on src/pages/docs/canvas/functions/canopy/cms-list.md
> +{{ cms_list('list-tag-123', { ordered: true, items:[ 'Item 1', 'Item 2', 'Item 3' ], class: 'list-decimal pl-5 space-y-2' }) }}
```suggestion
{{ cms_list('list-tag-123', { ordered: true, items: [ 'Item 1', 'Item 2', 'Item 3' ], class: 'list-decimal pl-5 space-y-2' }) }}
```

2024-07-21 23:34 UTC, jayan-blutui commented on src/pages/docs/canvas/functions/canopy/cms-video.md
> +{{ cms_video(name, { controls:..., autoplay: ..., sources: [{ url: '...', type: '...' },{url: '...', type: '...' }], class: '...' }) }}
```suggestion
{{ cms_video(name, { controls: ..., autoplay: ..., sources: [{ url: '...', type: '...' },{ url: '...', type: '...' }], class: '...' }) }}
```

2024-07-22 00:50 UTC, jayan-blutui approved these changes

2024-07-22 00:56 UTC, merged